/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imageprocessor;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Vittorio
 */
public class ImageProcessorUI extends javax.swing.JFrame {

    private ImageProcessor imageProcessor;

    /**
     * Creates new form ImageProcessorUI
     */
    public ImageProcessorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btnOpen = new javax.swing.JButton();
        lblURL = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        btnPictureOriginal = new javax.swing.JButton();
        btnPictureBW = new javax.swing.JButton();
        btnPictureReal = new javax.swing.JButton();
        btnPictureImaginary = new javax.swing.JButton();
        btnPictureAmplitude = new javax.swing.JButton();
        btnAnalysisStart = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mnSaveOriginal = new javax.swing.JMenuItem();
        mnSaveBW = new javax.swing.JMenuItem();
        mnSaveReal = new javax.swing.JMenuItem();
        mnSaveImaginary = new javax.swing.JMenuItem();
        mnSaveAmplitude = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fourier Image Processor");
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        btnOpen.setText("Open...");
        btnOpen.setPreferredSize(new java.awt.Dimension(90, 32));
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        getContentPane().add(btnOpen, gridBagConstraints);

        lblURL.setText("Chose Image");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        getContentPane().add(lblURL, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 5;
        getContentPane().add(lblImage, gridBagConstraints);

        btnPictureOriginal.setText("Original");
        btnPictureOriginal.setPreferredSize(new java.awt.Dimension(90, 32));
        btnPictureOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPictureOriginalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        getContentPane().add(btnPictureOriginal, gridBagConstraints);

        btnPictureBW.setText("B&W");
        btnPictureBW.setPreferredSize(new java.awt.Dimension(90, 32));
        btnPictureBW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPictureBWActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        getContentPane().add(btnPictureBW, gridBagConstraints);

        btnPictureReal.setText("Real");
        btnPictureReal.setEnabled(false);
        btnPictureReal.setPreferredSize(new java.awt.Dimension(90, 32));
        btnPictureReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPictureRealActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        getContentPane().add(btnPictureReal, gridBagConstraints);

        btnPictureImaginary.setText("Imaginary");
        btnPictureImaginary.setEnabled(false);
        btnPictureImaginary.setPreferredSize(new java.awt.Dimension(90, 32));
        btnPictureImaginary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPictureImaginaryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        getContentPane().add(btnPictureImaginary, gridBagConstraints);

        btnPictureAmplitude.setText("Amplitude");
        btnPictureAmplitude.setEnabled(false);
        btnPictureAmplitude.setPreferredSize(new java.awt.Dimension(90, 32));
        btnPictureAmplitude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPictureAmplitudeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        getContentPane().add(btnPictureAmplitude, gridBagConstraints);

        btnAnalysisStart.setText("Image Analysis");
        btnAnalysisStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalysisStartActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.insets = new java.awt.Insets(0, 36, 0, 36);
        getContentPane().add(btnAnalysisStart, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(32, 0, 0, 0);
        getContentPane().add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 11);
        getContentPane().add(filler2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jSeparator1, gridBagConstraints);

        jMenu1.setText("File");

        jMenu3.setText("Save");

        mnSaveOriginal.setText("Original");
        mnSaveOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSaveOriginalActionPerformed(evt);
            }
        });
        jMenu3.add(mnSaveOriginal);

        mnSaveBW.setText("Black And White");
        mnSaveBW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSaveBWActionPerformed(evt);
            }
        });
        jMenu3.add(mnSaveBW);

        mnSaveReal.setText("Real");
        mnSaveReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSaveRealActionPerformed(evt);
            }
        });
        jMenu3.add(mnSaveReal);

        mnSaveImaginary.setText("Imaginary");
        mnSaveImaginary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSaveImaginaryActionPerformed(evt);
            }
        });
        jMenu3.add(mnSaveImaginary);

        mnSaveAmplitude.setText("Amplitude");
        mnSaveAmplitude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSaveAmplitudeActionPerformed(evt);
            }
        });
        jMenu3.add(mnSaveAmplitude);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        choosePicture();
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnPictureOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPictureOriginalActionPerformed
        displayImage(imageProcessor.getOriginalImage());
    }//GEN-LAST:event_btnPictureOriginalActionPerformed

    private void btnPictureRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPictureRealActionPerformed
        displayImage(imageProcessor.getRealImage());
    }//GEN-LAST:event_btnPictureRealActionPerformed

    private void btnPictureBWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPictureBWActionPerformed
        displayImage(imageProcessor.getImage());
    }//GEN-LAST:event_btnPictureBWActionPerformed

    private void btnAnalysisStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalysisStartActionPerformed
        imageProcessor.launchAnalysis();

        JOptionPane.showMessageDialog(rootPane, "Analysis Complete", "Analysis Complete", JOptionPane.INFORMATION_MESSAGE);
        
        btnPictureAmplitude.setEnabled(true);
        btnPictureBW.setEnabled(true);
        btnPictureImaginary.setEnabled(true);
        btnPictureOriginal.setEnabled(true);
        btnPictureReal.setEnabled(true);

    }//GEN-LAST:event_btnAnalysisStartActionPerformed

    private void btnPictureImaginaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPictureImaginaryActionPerformed
        displayImage(imageProcessor.getImgImage());
    }//GEN-LAST:event_btnPictureImaginaryActionPerformed

    private void btnPictureAmplitudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPictureAmplitudeActionPerformed
        displayImage(imageProcessor.getAmplImage());
    }//GEN-LAST:event_btnPictureAmplitudeActionPerformed

    private void mnSaveOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSaveOriginalActionPerformed
        saveImage(imageProcessor.getOriginalImage());
    }//GEN-LAST:event_mnSaveOriginalActionPerformed

    private void mnSaveBWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSaveBWActionPerformed
        saveImage(imageProcessor.getImage());
    }//GEN-LAST:event_mnSaveBWActionPerformed

    private void mnSaveAmplitudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSaveAmplitudeActionPerformed
        saveImage(imageProcessor.getAmplImage());
    }//GEN-LAST:event_mnSaveAmplitudeActionPerformed

    private void mnSaveRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSaveRealActionPerformed
        saveImage(imageProcessor.getRealImage());
    }//GEN-LAST:event_mnSaveRealActionPerformed

    private void mnSaveImaginaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSaveImaginaryActionPerformed
        saveImage(imageProcessor.getImgImage());
    }//GEN-LAST:event_mnSaveImaginaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageProcessorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageProcessorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageProcessorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageProcessorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ImageProcessorUI().setVisible(true);
        });
    }

    void choosePicture() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        int result = fileChooser.showOpenDialog(rootPane);

        if (result == JFileChooser.APPROVE_OPTION) {
            //FileChooser used to allow the user to select desired file
        }

        File image = fileChooser.getSelectedFile();

        if (image == null) { // no image selected
            return;
        }

        lblURL.setText(image.toString());

        try {
            imageProcessor = new ImageProcessor(ImageIO.read(image));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Something went wrong.", "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(ImageProcessorUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        displayImage(imageProcessor.getImage());

    }

    void displayImage(BufferedImage image) {
        ImageIcon icon = new ImageIcon(ImageProcessor.maxSize(image, 300));

        lblImage.setIcon(icon);

        this.pack();
    }

    void saveImage(BufferedImage image) {
        File file = new File("image.png");

        try {
            ImageIO.write(image, "png", file);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "An error occurred while exporting the image.", "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(ImageProcessorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalysisStart;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnPictureAmplitude;
    private javax.swing.JButton btnPictureBW;
    private javax.swing.JButton btnPictureImaginary;
    private javax.swing.JButton btnPictureOriginal;
    private javax.swing.JButton btnPictureReal;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblURL;
    private javax.swing.JMenuItem mnSaveAmplitude;
    private javax.swing.JMenuItem mnSaveBW;
    private javax.swing.JMenuItem mnSaveImaginary;
    private javax.swing.JMenuItem mnSaveOriginal;
    private javax.swing.JMenuItem mnSaveReal;
    // End of variables declaration//GEN-END:variables
}
